SELECT E.ID
FROM ECOLI_DATA E
WHERE E.PARENT_ID IN (SELECT F.ID FROM ECOLI_DATA F
                     WHERE F.PARENT_ID IN (SELECT G.ID FROM ECOLI_DATA G
                                         WHERE G.PARENT_ID IS NULL)) 
ORDER BY E.ID;