SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
LEFT JOIN ITEM_TREE T1 ON I.ITEM_ID = T1.ITEM_ID
LEFT JOIN ITEM_TREE T2 ON I.ITEM_ID = T2.PARENT_ITEM_ID
WHERE T2.PARENT_ITEM_ID IS NULL
ORDER BY I.ITEM_ID DESC;
