SELECT 
    C.CAR_ID, 
    C.CAR_TYPE, 
    ROUND(C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100 * 30, 0) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR C
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE
WHERE 
    C.CAR_TYPE IN ('세단', 'SUV')
    AND D.DURATION_TYPE = '30일 이상'
    AND NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE H.CAR_ID = C.CAR_ID
        AND ((H.START_DATE <= '2022-11-30') AND (H.END_DATE >= '2022-11-01'))
    )
    AND ROUND(C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100 * 30, 0) >= 500000
    AND ROUND(C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100 * 30, 0) < 2000000
GROUP BY 
    C.CAR_ID, C.CAR_TYPE
ORDER BY 
    FEE DESC, 
    C.CAR_TYPE ASC, 
    C.CAR_ID DESC;
