WITH RECURSIVE GENERATION_INFO AS (
    -- 1단계: 각 세대를 재귀적으로 계산
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA E
    JOIN GENERATION_INFO G ON E.PARENT_ID = G.ID
),
NO_CHILDREN AS (
    -- 2단계: 자식이 없는 개체 찾기
    SELECT G.GENERATION, G.ID
    FROM GENERATION_INFO G
    LEFT JOIN ECOLI_DATA E ON G.ID = E.PARENT_ID
    WHERE E.PARENT_ID IS NULL
)
-- 3단계: 세대별 자식 없는 개체 수를 세고 결과를 정렬
SELECT COUNT(ID) AS COUNT, GENERATION
FROM NO_CHILDREN
GROUP BY GENERATION
ORDER BY GENERATION ASC;
