WITH DISCOUNT AS ( 
    SELECT CAR_TYPE, 
           CAST(REGEXP_REPLACE(DURATION_TYPE, '[^0-9]', '') AS UNSIGNED) AS DURATION_TYPE,
           CAST(REGEXP_REPLACE(DISCOUNT_RATE, '[^0-9]', '') AS UNSIGNED) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
),
HISTORY AS (
    SELECT H.HISTORY_ID, 
           C.DAILY_FEE,
           DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    INNER JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT DISTINCT 
       H.HISTORY_ID,
       ROUND(
           MIN(
               CASE 
                   WHEN H.DURATION >= D.DURATION_TYPE THEN H.DURATION * H.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100
                   ELSE H.DURATION * H.DAILY_FEE 
               END
           ) OVER (PARTITION BY H.HISTORY_ID), 0
       ) AS FEE
FROM HISTORY H
CROSS JOIN DISCOUNT D
ORDER BY FEE DESC, H.HISTORY_ID DESC;
