SELECT CASE WHEN DATE_FORMAT(DATETIME, '%H') LIKE '0%'
THEN SUBSTR(DATE_FORMAT(DATETIME, '%H'), 2, 2) 
ELSE DATE_FORMAT(DATETIME, '%H') END AS HOUR, 
COUNT(DATETIME) AS COUNT
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%H') >= '09'
AND DATE_FORMAT(DATETIME, '%H') <= '19'
GROUP BY DATE_FORMAT(DATETIME, '%H')
ORDER BY DATE_FORMAT(DATETIME, '%H');
