SELECT E.ID, E.GENOTYPE, 
(SELECT GENOTYPE FROM ECOLI_DATA 
 WHERE E.PARENT_ID = ID) AS PARENT_GENOTYPE
FROM ECOLI_DATA E
WHERE E.GENOTYPE & (SELECT GENOTYPE FROM ECOLI_DATA 
 WHERE E.PARENT_ID = ID) = (SELECT GENOTYPE FROM ECOLI_DATA 
 WHERE E.PARENT_ID = ID);