SELECT DISTINCT I.ID, N.FISH_NAME, I.LENGTH
FROM (
    SELECT ID, FISH_TYPE, LENGTH,
           RANK() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS rnk
    FROM FISH_INFO
) I
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.rnk = 1
ORDER BY I.ID;
