SELECT I.ID, N.FISH_NAME, MAX_LENGTHS.LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS MAX_LENGTHS ON I.FISH_TYPE = MAX_LENGTHS.FISH_TYPE AND I.LENGTH = MAX_LENGTHS.LENGTH
ORDER BY I.ID;
