SELECT
    BOOK.BOOK_ID,
   
    (SELECT AUTHOR_NAME
     FROM AUTHOR
     WHERE AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID) AS AUTHOR_NAME,
     DATE_FORMAT(BOOK.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLSIHED_DATE
FROM BOOK
WHERE CATEGORY = '경제'
ORDER BY PUBLISHED_DATE;
